name: Build & Release LaTeX Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      PDF_FILENAME: Filippo-Spinella_Resume.pdf

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      
      - name: Rename PDF file
        run: mv cv.pdf ${{ env.PDF_FILENAME }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDF
          path: ${{ env.PDF_FILENAME }}

      - name: Create new release and upload PDF
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PDF_FILENAME }}
